In [49]:
# 1. Write a Python Program to find sum of array?

In [3]:
import numpy as np 
       
lst = [20, 2, .2, 10, 4]  
   
print("\nSum of arr : ", np.sum(lst)) 


Sum of arr :  36.2


In [ ]:
# 2. Write a Python Program to find largest element in an array?

In [5]:
lst = []
num = int(input("Enter the size of the array: "))
print("Enter array elements: ")
for i in range(num):
  number = int(input())
  lst.append(number)
print(max(lst))

Enter the size of the array: 5
Enter array elements: 
20
10
50
60
3
60


In [ ]:
# 3. Write a Python Program for array rotation?

In [21]:
# Method 1
import numpy as np
m=np.arange(1,7, 1).reshape((3, 2))
m

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
np.rot90(m)

array([[2, 4, 6],
       [1, 3, 5]])

In [22]:
# Method 2
import numpy as np
m = np.array([[1,2], [3,4], [5,6]], int)
m

array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
np.rot90(m)

array([[2, 4, 6],
       [1, 3, 5]])

In [ ]:
# 4. Write a Python Program to Split the array and add the first part to the end?

In [43]:
def split(arr, n, k): 
   b = arr[:k]
   return (arr[k::]+b[::])
          
  
arr = [7,10,15,20,99,101]
n = len(arr)
position = 3

arr = split(arr, n, position)
for i in range(0, n): 
    print(arr[i], end = ' ')

20 99 101 7 10 15 

In [ ]:
# 5. Write a Python Program to check if given array is Monotonic?

In [48]:
# Check if given array is Monotonic
# An array is monotonic if it is either monotone increasing or monotone decreasing.
def Monotonic(Arr):
  
    return (all(Arr[i] <= Arr[i + 1] for i in range(len(Arr) - 1)) or
            all(Arr[i] >= Arr[i + 1] for i in range(len(Arr) - 1)))
  
Arr = [1,3,5,99]
  
print(Monotonic(Arr))

True
